### ISSUE TITLE
Can't compile with gcc 15.1.1

### ISSUE THREAD

**Issue by CosmicHeron** [yquake2/ref_gl4#3]
I maintain the yamagi-quake2-ref_gl4 (and git version) on AUR and trying to build with gcc 15.1.1. 
<details>
<summary>Errors reported when running `make` on the cleanly cloned repository</summary>

```
===> Building ref_gl4.so
make release/ref_gl4.so
make[1]: Entering directory '/tmp/tmp.Cazqkai9qg'
===> CC src/client/refresh/gl4/gl4_draw.c
In file included from src/client/refresh/gl4/header/../../../vid/header/../../../common/header/common.h:32,
from src/client/refresh/gl4/header/../../../vid/header/ref.h:30,
from src/client/refresh/gl4/header/../../ref_shared.h:30,
from src/client/refresh/gl4/header/local.h:57,
from src/client/refresh/gl4/gl4_draw.c:28:
src/client/refresh/gl4/header/../../../vid/header/../../../common/header/shared.h:49:15: error: cannot use keyword ‘false’ as enumeration constant
49 | typedef enum {false, true}  qboolean;
|               ^~~~~
src/client/refresh/gl4/header/../../../vid/header/../../../common/header/shared.h:49:15: note: ‘false’ is a keyword with ‘-std=c23’ onwards
make[1]: *** [Makefile:428: build/ref_gl4/src/client/refresh/gl4/gl4_draw.o] Error 1
make[1]: Leaving directory '/tmp/tmp.Cazqkai9qg'
make: *** [Makefile:417: ref_gl4] Error 2
```

</details>
<details>
<summary>Errors reported when trying to build the package</summary>

```
==> Starting build()...
make: Entering directory '/tmp/makepkg/yamagi-quake2-ref_gl4/src/ref_gl4-1.08'
===> Building ref_gl4.so
make release/ref_gl4.so
make[1]: Entering directory '/tmp/makepkg/yamagi-quake2-ref_gl4/src/ref_gl4-1.08'
===> CC src/client/refresh/gl4/gl4_draw.c
===> CC src/client/refresh/gl4/gl4_image.c
===> CC src/client/refresh/gl4/gl4_light.c
In file included from src/client/refresh/gl4/header/../../../vid/header/../../../common/header/common.h:32,
from src/client/refresh/gl4/header/../../../vid/header/ref.h:30,
from src/client/refresh/gl4/header/../../ref_shared.h:30,
from src/client/refresh/gl4/header/local.h:57,
from src/client/refresh/gl4/gl4_draw.c:28:
src/client/refresh/gl4/header/../../../vid/header/../../../common/header/shared.h:49:15: error: cannot use keyword ‘false’ as enumeration constant
49 | typedef enum {false, true}  qboolean;
|               ^~~~~
src/client/refresh/gl4/header/../../../vid/header/../../../common/header/shared.h:49:15: note: ‘false’ is a keyword with ‘-std=c23’ onwards
make[1]: *** [Makefile:426: build/ref_gl4/src/client/refresh/gl4/gl4_draw.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from src/client/refresh/gl4/header/../../../vid/header/../../../common/header/common.h:32,
from src/client/refresh/gl4/header/../../../vid/header/ref.h:30,
from src/client/refresh/gl4/header/../../ref_shared.h:30,
from src/client/refresh/gl4/header/local.h:57,
from src/client/refresh/gl4/gl4_image.c:28:
src/client/refresh/gl4/header/../../../vid/header/../../../common/header/shared.h:49:15: error: cannot use keyword ‘false’ as enumeration constant
49 | typedef enum {false, true}  qboolean;
|               ^~~~~
src/client/refresh/gl4/header/../../../vid/header/../../../common/header/shared.h:49:15: note: ‘false’ is a keyword with ‘-std=c23’ onwards
In file included from src/client/refresh/gl4/header/../../../vid/header/../../../common/header/common.h:32,
from src/client/refresh/gl4/header/../../../vid/header/ref.h:30,
from src/client/refresh/gl4/header/../../ref_shared.h:30,
from src/client/refresh/gl4/header/local.h:57,
from src/client/refresh/gl4/gl4_light.c:28:
src/client/refresh/gl4/header/../../../vid/header/../../../common/header/shared.h:49:15: error: cannot use keyword ‘false’ as enumeration constant
49 | typedef enum {false, true}  qboolean;
|               ^~~~~
src/client/refresh/gl4/header/../../../vid/header/../../../common/header/shared.h:49:15: note: ‘false’ is a keyword with ‘-std=c23’ onwards
make[1]: *** [Makefile:426: build/ref_gl4/src/client/refresh/gl4/gl4_image.o] Error 1
make[1]: *** [Makefile:426: build/ref_gl4/src/client/refresh/gl4/gl4_light.o] Error 1
make[1]: Leaving directory '/tmp/makepkg/yamagi-quake2-ref_gl4/src/ref_gl4-1.08'
make: *** [Makefile:417: ref_gl4] Error 2
make: Leaving directory '/tmp/makepkg/yamagi-quake2-ref_gl4/src/ref_gl4-1.08'
==> ERROR: A failure occurred in build().
Aborting...
error: failed to build 'yamagi-quake2-ref_gl4-1.08-3':
error: packages failed to build: yamagi-quake2-ref_gl4-1.08-3
paru failed with exit status 1.
```

</details>

**Comment by atsb** [comment]
Thank you!  I'll fix it immediately, sorry for the delay

**Comment by atsb** [comment]
I do all my tags like that, doesn't matter.

**Comment by atsb** [comment]
Fantastic!  Thanks, yeah, C23 came at the wrong time and with such differences with clang and gcc, it is a disaster

**Comment by Yamagi** [comment]
I don't know what they were thinking by altering `false` and `true` in C23. Yes, it's nicer to have them as language keywords. But it break so much existing code for such a little gain...

**Comment by atsb** [comment]
> I don't know what they were thinking by altering `false` and `true` in C23. Yes, it's nicer to have them as language keywords. But it break so much existing code for such a little gain...

That's the issue, they aren't thinking now.  C99 was perfect, don't fix what isn't broken and certainly don't make C complicated.

**Comment by atsb** [comment]
So I installed GCC 15.2.1 on my machine along with Arch.  It builds perfectly fine for me using this version of GCC, no issues at all.

<img width="912" height="482" alt="Image" src="https://github.com/user-attachments/assets/f859a4fe-9b21-4f1b-b322-30053d319355" />

Are you sure you've pulled all the latest changes?

**Comment by CosmicHeron** [comment]
That's the odd thing, if I just clone the repo, cd into it and run make, it builds without errors. But if I try to build [yamagi-quake2-ref_gl4-git](https://aur.archlinux.org/packages/yamagi-quake2-ref_gl4-git) with makepkg, which just automates that process it fails with those errors. I don't have any other Arch systems on hand at the moment, but you can clone that AUR package and run `makepkg -s` inside it and see if it works? If it works for you then it's something about my system, if not I'll have to check if makepkg sets up some environment variables in the background that might be the culprit.

**Comment by CosmicHeron** [comment]
I think I found the issue; when running makepkg CFLAGS are sourced from `/etc/makepkg.conf` which are then used by the compiler. I manually swapped them in and out and it's the `-Wp,-D_FORTIFY_SOURCE=3` flag that's causing the errors to pop up.

By default these are the CFLAGS used when the compiler is invoked by the PKGBUILD script:
```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
```
These flags are not set when running make normally, so that's why it doesn't fail when building it like that.
